sudo: required
dist: trusty
language: python
python:
  - "3.6"
addons:
  chrome: stable
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - pip install -r requirements.txt
  - nohup sudo Xvfb :10 -ac &
  - export DISPLAY=:10
script:
  - python motion.py
after_success:
  - fab deploy
cache:
  directories:
  - site